version: "3.8"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "Admin123"
      MYSQL_DATABASE: "hex_test"
    volumes: 
      - ./testdb:/docker-entrypoint-initdb.d
    healthcheck:
      retries: 10
      interval: 1s
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
    ports:
      - "3306:3306"

  grpc_test:
    build:
      context: .
      target: builder
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["go", "test", "-v", "./..."]


  grpc: 
    build:
      context: .
      target: production
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
#      grpc_test:
#        condition: service_completed_successfully
